#pragma once

#define AUTHORS_A "Paul Klein"
#define AUTHORS_B "Paul Klein"
#define AUTHORS_C "Paul Klein"
#define AUTHORS_D "Paul Klein"
#define AUTHORS_E "Sam Diehl"
#define AUTHORS_F "Sam Diehl"
#define AUTHORS_G "Sam Diehl"
#define AUTHORS_H "Sam Diehl"
#define AUTHORS_I "Sam Diehl"
#define AUTHORS_J "Sam Diehl"
#define AUTHORS_K "Paul Klein"
#define AUTHORS_L "Paul Klein"
#define AUTHORS_M "Paul Klein"
#define AUTHORS_N ""
