#pragma once

#define AUTHORS_A "Lukas Rothenberger"
#define AUTHORS_B ""
#define AUTHORS_C ""
#define AUTHORS_D ""
#define AUTHORS_E "Sam Diehl"
#define AUTHORS_F "Sam Diehl"
#define AUTHORS_G "Sam Diehl"
#define AUTHORS_H "Sam Diehl"
#define AUTHORS_I "Sam Diehl"
#define AUTHORS_J "Sam Diehl"
#define AUTHORS_K ""
#define AUTHORS_L ""
#define AUTHORS_M ""
#define AUTHORS_N ""
